version: 1
disable_existing_loggers: false
formatters:
  default:
    "()": uvicorn.logging.DefaultFormatter
    fmt: "%(levelprefix)s %(message)s"
    use_colors: false
  access:
    "()": uvicorn.logging.AccessFormatter
    fmt: >-
      %(levelprefix)s - "%(request_line)s"
      %(status_code)s
    use_colors: false
handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stdout
  access:
    formatter: access
    class: logging.StreamHandler
    stream: ext://sys.stdout
loggers:
  uvicorn:
    handlers: [default]
    level: INFO
    propagate: false
  uvicorn.error:
    handlers: [default]
    level: INFO
    propagate: false
  uvicorn.access:
    handlers: [access]
    level: INFO
    propagate: false
  ml:
    handlers: [default]
    level: INFO
    propagate: false
root:
  level: DEBUG
  handlers: [default]
